#!/data/data/com.termux/files/usr/bin/sh
cd /data/data/com.termux/files/home/ash_min
exec /data/data/com.termux/files/home/ash_min/.venv/bin/uvicorn \
  app_star:app --host 127.0.0.1 --port 8080 --workers 1
